### PR TITLE
Preliminary card templates

### PR DESCRIPTION
**Pull request by cielago**
some preliminary card templates. the influence stuff is all speculative. based these on the format you used in the netrunner cards db.

### CODE REVIEW

**Comment by Alsciende** [comment]
That's pretty cool, thanks. To answer your questions:

- "flavor" is indeed missing
- "pack_code", "deck_limit", "quantity" will be in another file, PackSlot.json. That will allow one card to be in many packs (either reeditions or promos). I guess "illustrator" and "flavor" should be there, too.
- I prefer is_conflict and is_dynasty ; one reason is that only those two values are meaningful, so an extra entity is a bit overkill ; another reason is that I already have an entity named Deck ^_^

**Comment by platypusL5R** [comment]
A small comment on the is_conflict/is_dinasty talk. There seem to be extra possibilities: stronghold (which starts in play and is unique) and provinces (which start in play and need 5 of them). Not sure if it should be only one extra is_starting value that includes both types.

**Comment by rtbreedlove** [comment]
@platypusL5R That was my reasoning behind the string.

**Comment by dodgepong** [comment]
Is it worthwhile to suggest making keywords a list of strings, rather than a single string that must be parsed?

**Pull request merged**
